### ISSUE TITLE
Non-consistent nan value for KL divergence

### ISSUE THREAD

**Issue by vb690** [pavlin-policar/openTSNE#108]
##### Expected behaviour

When calling `TSNE.fit()` on the same numpy array I expect:

1. The KL divergence to not be a `nan`
2. The appearence of `nan`in the KL divergence to not depend on ~~the specific  array slice considered~~ the chosen value of perplexity.

##### Actual behaviour

Parameters Tested (what is not mentioned is kept at the default value):
```python
perplexity = [100, 200, 300, 500]
distance = ["euclidean", "cosine"]
n_iter=2000
learning_rate=[200, X.shape[0] // 12]
n_jobs=4
```

Data Source:
```python
X = np.random.randint(-1, 1, shape=(600000, 100))
X_test_1 = X[:300000, :]
X_test_2 = X[:6000, :]
```
`X` is an embedding extracted using `tensorflow.keras.LSTM`.
`X` does not contain any "weird" value (e.g. `nan` or `inf`)

~~`X_test_1` leads to `nan` KL Divergence since the first 50 iterations~~
~~`X_test_2` shows normal behaviour~~
~~Random and bigger slices of  `X` also show normal behaviour~~

Values of perplexity above 100 leads to `nan` KL Divergence since the first 50 iterations

##### Steps to reproduce the behavior

It is hard to outline the steps for reproducing this behaviour since it appears to be data dependent. 
I have different behaviours on different slices of the input array while a colleague of mine reported a silent exit on one data source (of shape ~(10000, 250)) while normal behaviour on another.

**UPDATE**
The problem apparently lies in the parameter `perplexity`: values above 100 will lead to `nan` KL Divergence, is this behaviour expected?

**Comment by pavlin-policar** [comment]
I've also noticed this behaviour and, as you said, it's very inconsistent and hard to reproduce. I've been meaning to dig into it for a while, but quite simply hadn't had the time yet. Thanks for reporting this though.

You shouldn't be worried about this, because even though the KL divergence is reported as NaN, the embeddings are all still calcualted properly. I would guess that there's some minor bug in the KL divergence reporting, maybe some conversions between cython and python.

**Comment by vb690** [comment]
That is some amazing news!

Thank you for the answer and for making openTSNE available to everyone.
