### ISSUE TITLE
openTSNE binaries for OS X are only 10.14+

### ISSUE THREAD

**Issue by markotoplak** [pavlin-policar/openTSNE#150]
openTSNE binaries should also available for older Macs. For example, Orange pypi download, for example, is supported until 10.9. As is numpy's. I found about 10.14 limit when trying to build some installers on travis with older MacOS.

10.14 seems like a high limit. There are surely still some users on older platforms; 10.13 is even still officially supported. Or are there any technological reasons for this decision?

I am not sure what now happens to Orange3 users that use its official dmg on older Macs... They won't get install warnings because packages there are already extracted, which is good. I only hope it does not crash while usage.

**Comment by pavlin-policar** [comment]
I don't think this would actually be that easy to fix. We build the packages on Azure Pipelines, and the earliest version of MacOS they support is 10.14 ([docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software)). GH actions, for example, only provides VM images for 10.15 ((docs)[https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners]), so that's even worse. The earliest MacOS VM I've been able to find is on Travis, and is 10.11 ([docs](https://docs.travis-ci.com/user/reference/osx/)). I guess Orange is built on Travis.

I'm not sure I want to go changing the build pipeline for this unless it's absolutely necessary. I would kind of expect Travis to eventually follow suit and drop older versions as well.

**Comment by markotoplak** [comment]
Perhaps see https://github.com/ales-erjavec/orange3-wheels/. This repo somehow manages to build Orange for 10.9.

**Comment by pavlin-policar** [comment]
Actually, it seems to be quite easy. We just have to set the environmental variable `MACOSX_DEPLOYMENT_TARGET=10.6` and that's it. I can easily do this, but I have no way of checking that this actually works. I don't have access to any such old MacOS system.
