### ISSUE TITLE
how can I use on my own image dataset？

### ISSUE THREAD

**Issue by Tomlk** [pavlin-policar/openTSNE#203]
could you please provide a demo for  local image dataset？

**Comment by pavlin-policar** [comment]
openTSNE is a general-purpose visualization library that can handle all kinds of data. By default, it supports any data you give it in a matrix format e.g. a numpy array or a scipy sparse matrix. What you're asking is to provide a demo on how to read image files from disk, which isn't a problem that openTSNE attempts to solve. It's up to you how you read in the data and turn it into usable matrix formats.

That said, there are plenty of tutorials on how to read in images from disk. PIL can do it, openCV can do it, scipy can do it. I'm sure you can find a myriad of tutorials online if you search for something like "scikit-learn image classification", then just instead of classification, you can use openTSNE to visualize the matrix.
