### ISSUE TITLE
Create an affinity object with precomputed affinity matrix

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#216]
If I have a sparse affinity matrix stored in `P`, I can run openTSNE as follows:

```
from openTSNE import TSNE
from openTSNE.affinity import Affinities

A = Affinities()
A.P = P
Z = TSNE().fit(affinities = A)
```

I was wondering it would make sense to implement the following API:
```
Z = TSNE().fit(affinities = Affinities(P))
```

**Comment by pavlin-policar** [comment]
Hmm, the `Affinities` object is really meant more of as a base-class, and I never intended it to be used in this way. But I suppose there is no reason this should not work fine. There are two options, I think. One is the API you suggest `Affinities(P)`, but I think making a new class doing basically the same thing called `PrecomputedAffinities(P)` would fit more nicely into the API. Since we already have the `PrecomputedNeighbors` KNN index. That would definitely make sense. 

Since you already have a use-case in mind, would you be willing to take a crack at it?
