### ISSUE TITLE
`latest` version of ReadTheDocs not rendering Python code

### ISSUE THREAD

**Issue by MattScicluna** [pavlin-policar/openTSNE#222]
##### Expected behaviour
![Screen Shot 2022-12-14 at 8 14 34 PM](https://user-images.githubusercontent.com/19255250/207749209-f6832d6f-1073-45c0-9b45-b2da8519b2a9.png)

##### Actual behaviour
![Screen Shot 2022-12-14 at 8 14 16 PM](https://user-images.githubusercontent.com/19255250/207749164-22552251-d3a8-4b7a-a702-e74795d03e58.png)

##### Steps to reproduce the behavior
Go to: https://opentsne.readthedocs.io/en/latest/examples/02_advanced_usage/02_advanced_usage.html

**Comment by pavlin-policar** [comment]
Hi, thanks for reporting this. I have no idea why this is happening; there haven't been any changes in the documentation for a very long time. Bizarrely, the code blocks seem to be hidden when viewing the [`latest`](https://opentsne.readthedocs.io/en/latest/examples/02_advanced_usage/02_advanced_usage.html) version of the docs, but show up when viewing the [`stable`](https://opentsne.readthedocs.io/en/stable/examples/02_advanced_usage/02_advanced_usage.html), which is openTSNE v0.6.2 works fine.

I've set the default readthedocs page to point to `stable`, which makes more sense  anyways, since most people will be downloading openTSNE from PyPI and not cloning the master branch. So this should fix the immediate problem.

If anyone has any idea on how to fix this, I'd appreciate the help.

**Comment by pavlin-policar** [comment]
I've re-run the documentation build, and it seems to be working fine in both instances now. I guess something must have gone wrong with the build, but there were no errors in the build log. Either way, I'd say this is now resolved.

**Comment by dkobak** [comment]
I google a bit and found this: https://github.com/stan-dev/cmdstanpy/issues/178 and https://github.com/stan-dev/cmdstanpy/pull/181. The fix there was to use `code::` instead of `code-block::` and to change `ipython3` blocks to `python`. 

You use `.. code:: ipython3` blocks e.g. in https://raw.githubusercontent.com/pavlin-policar/openTSNE/master/docs/source/examples/02_advanced_usage/02_advanced_usage.rst, so perhaps replacing `ipython3` with `python` may help? No idea.

**Comment by pavlin-policar** [comment]
Thanks for the links, but it should be fixed now. I guess it was just an error in the readthedocs build that didn't show up in the build logs.
