### ISSUE TITLE
Sparse matrix support

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#28]
Does `fastTSNE` currently support sparse matrices as input (i.e. `scipy.sparse` objects)? I remember reading that UMAP does support them, so I assume `pynndescent` should, but I did not look deeper into that.

I also wonder how efficient `pynndescent` for huge sparse matrices is, compared e.g. to https://github.com/facebookresearch/pysparnn that I found by googling `approximate nearest neighbour sparse`. I also came across this https://github.com/RUSH-LAB/Flash, described here https://arxiv.org/pdf/1709.01190.pdf. Don't know what other libraries are there.

This isn't very useful for single cell transcriptomics, but is relevant for text-based datasets with millions of samples and millions (!) of features.

**Comment by dkobak** [comment]
I went ahead and asked the same question here: https://github.com/lmcinnes/pynndescent/issues/6.

**Comment by dkobak** [comment]
PS. Actually, I went ahead and asked the same thing here: https://github.com/lmcinnes/pynndescent/issues/6

**Comment by pavlin-policar** [comment]
No, sparse data are currently not supported. Neither of the nearest neighbor methods used support it. For exact search, scikit-learn uses brute force for sparse matrices (so very slow) and pynndescent apparently doesn't support it at all (as per your issue). Ideally, we would need an exact and approximate search method for sparse data - I don't like the idea of supporting one type of search and not the other.

It is also fairly straightforward to replace the KNN libraries with anything else - you just need to subclass the `Affinity` class and you can compute affinities in any way you want. This isn't documented anywhere yet, but the functionality is already there. A simple example would be

```python
affinities = MySparseAffinities(X, ...)
initialization = init_scheme.pca(X, n_components=2)
embedding = TSNEEmbedding(initialization, affinities, perplexity=50, learning_rate=500)
embedding.optimize(250, exaggeration=12, momentum=0.5, inplace=True)
embedding.optimize(750, momentum=0.8, inplace=True)
```

I also remember hearing somewhere that t-SNE doesn't scale well with dimensions (I've got no references or anything to back this up, just word of mouth) and if that is the case, I don't know how useful t-SNE might be at all. I don't know whether or not this is true e.g. MNIST has 784 dimensions and was the showcase example for t-SNE. 784 isn't that much, but it's not trivial either, even for sc data we reduce the dimensions down to 50 or 100 PCs.

I have practically no experience with text data, but if you have a large sparse matrix, you might be able to get decent results by first running it through SVD.

**Comment by pavlin-policar** [comment]
> I don't see much need for exact sparse NN to be honest.

Neither do I TBH, but I prefer to have consistent behaviour where reasonable/possible. I suppose, in this case, it may not be reasonable, so I suppose I'd be alright if an informative error was raised. And even then, some metrics aren't supported and it all becomes very messy.

In any case, one of the requirements for anything we include here is that it's easily installable and distributable, at least through conda if not through pypi. pysparnn would be easier to incorporate given that it's in pure python. However, it's not on pypi and really only supports cosine distance well. It also includes euclidean distance, but the docstring says that it's slow. Flash is C++ so we'd have to include cython bindings to it, and add it to the conda recipe in order to compile it.

Since UMAP supports sparse data with pynndescent, I guess it may most straightforward to just figure out what they changed and incorporate that here as well.

I'm open to supporting sparse data in some reasonable way, but it's not high on my list of priorities here. I think I've made the Affinities API fairly extensible so it's easy to use something like this (after I properly document it). I've got a few ideas on how to incorporate this, and if you're willing to work on this, I'd be happy to discuss further.

> I think Leland means that the similarity kernel that t-SNE uses works worse in high dimensions than the similarity kernel that UMAP uses.

I haven't really gone through how UMAP works - I feel as though the maths are a over my head for the time being, so I can't really comment.

From what I can tell, t-SNE is at least somewhat sensitive to noise, and the more dimensions we have, the more opportunity for noise to occur. I've noticed that without doing some kind of dimensionality reduction before t-SNE I'd often get meaningless embeddings, but after doing some feature selection or PCA that would be fixed. That kind of seems to be in line with saying that t-SNE doesn't scale well to high dimensions, so I don't know... I have limited experience with text data, so I don't know if this happens there also, but I suspect it shouldn't be too different.

I haven't played around with UMAP as much as with t-SNE, but I suspect it faces the above issues also, since these are things that would pop up in the KNN graph construction and not during the optimization itself.

> I've never seen any direct empirical demonstration of this.

Me either, but it would be really interesting to see.

**Comment by dkobak** [comment]
Update: `pynndescent` now supports sparse matrices (https://github.com/lmcinnes/pynndescent/pull/16). Does it mean that openTSNE will now support it without any need to change anything?

**Comment by pavlin-policar** [comment]
Well, they'd need to do a release of `pynndescent` first. And also, at the time I was writing this code, I was still supporting 32bit systems, so copying over the files from `pynndescent` into this repo and making changes as needed was much simpler than trying to patch the library afterwards. Thankfully, we don't support 32 bit systems any more, so depending on it outright is the much better option.

So there are two options: 
1. The easiest and quickest thing to do would be to just copy over their new files here or
2. Remove the current implementation and properly depend on `pynndescent`, then wait for a release where the sparse support will be added.

The second is definitely the way to go, but will require waiting for them to make a release. If you want to play around with it straight away, the first method is definitely much simpler.

**Comment by pavlin-policar** [comment]
However, it's also worth mentioning that we are considering replacing `pynndescent` with something faster. We have mixed feelings about numba in general and having run some benchmarks against FIt-SNE, the part I wrote in cython is as fast as the C++ implementation, but the NN search done by numba and `pynndescent` is substantially slower than Annoy (granted this is only noticeable with large data sets). I have high hopes for the recently merged https://github.com/lmcinnes/pynndescent/pull/12, but I haven't had time to look at it yet.

In any case, even if we do go ahead and replace `pynndescent` with something else, I'll be sure to leave it in as optional, so if you've got the stuff installed, it'll run. Also, the sparse support is appealing.

**Comment by dkobak** [comment]
Hmm. I remember looking at the figures here https://github.com/erikbern/ann-benchmarks and my impression was that `pynndescenent` is faster than `annoy`, not slower. But I never really looked into it myself.

**Comment by jlmelville** [comment]
I think in https://github.com/erikbern/ann-benchmarks, the time the index takes to build isn't included, only the search time. At any rate, this corresponds with what was mentioned in https://github.com/lmcinnes/umap/issues/213 and my own experience with HNSW vs Annoy.

**Comment by pavlin-policar** [comment]
As it turns out, one of the reasons it may have been slow was because I was calling it incorrectly. I had assumed the API to pynndescent to be identical to the scikit-learn API, and had never really bothered to check . I'll have to rerun the benchmarks to compare the speeds again. This was my bad and I'll push the fix up ASAP. This library should be considerably faster afterwards when using approximate neighbor search.

But as @jlmelville points out, for the usual t-SNE usage, it's the build time that's important, not the query time, so those graphs might not be the most relevant. Honestly, I never really bothered looking very much into NN search

**Comment by pavlin-policar** [comment]
To address my previous comment:

>have been slow was because I was calling it incorrectly

This was not the case. I had been calling it properly. But I had found the following (if memory serves):
- building the index for a lot of neighbors is slower than annoy
- however, querying seems to be quite fast
- so, I build the index on 15 neighbors (so it's fairly fast) and query the missing neighbors that we need for t-SNE (so the standard 30 perplexity will query 90 neighbors on an index built on 15 neighbors).

I compared the results against building the entire index on 90 neighbors and I couldn't see any difference. If this seems problematic, it's fairly simple to implement a KNN index and use that.

To address sparse support: As of 40d721b819146067b030b8d752b3c2871d2be568 we properly depend on `pynndescent`. However, sparse support in the release seems highly unstable and I haven't been able to get a single example working with sparse input.

It seems that the parallelization works properly though.

This is no longer directly an openTSNE issue, but a `pynndescent` issue, so I'm closing this. I see they've fixed a couple bugs from the last release, so hopefully, they get that sorted out asap. @dkobak I have made it very easy to extend the library so if you want to use some other algorithm that supports sparse data, you just need to extend [`KNNIndex`](https://github.com/pavlin-policar/openTSNE/blob/master/openTSNE/nearest_neighbors.py#L7-L51) and use that as the `neighbors` parameter.

**Comment by dkobak** [comment]
> As of 40d721b we properly depend on pynndescent.

This is great!

> However, sparse support in the release seems highly unstable and I haven't been able to get a single example working with sparse input.

Hmm. Is it something that we/you should raise an pynndescent issue about? Do you have a reproducible example that you could post there? Or do you think they are aware of the problem and are already working on solving it?

**Comment by pavlin-policar** [comment]
I've opened an issue on their repo: https://github.com/lmcinnes/pynndescent/issues/65
