### ISSUE TITLE
Why does n_iter correspond to the number of iterations without exaggeration?

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#64]
Just noticed that `n_iter` is (everywhere) defined as

> The number of iterations to run in the normal optimization regime.

Isn't it at odds with all other t-SNE implementations? At least FIt-SNE wrappers, scikit-learn, the original Barnes-Hut C++ wrappers, -- all define n_iter (or however this parameter is called) as the _total_ number of iterations, including early exaggeration phase.

Did you on purpose deviate from this historical "convention"?

**Comment by pavlin-policar** [comment]
> Isn't it at odds with all other t-SNE implementations?

It is.

> Did you on purpose deviate from this historical "convention"?

I did. I find this "convention" questionable, especially with the addition of the *late exaggeration phase* George proposed. What would we do then when `n_iter=1000`? Do we run 250 early exaggeration steps, 500 regular steps, and 250 late exaggeration steps? I find that more confusing than it needs to be. I think it's better to be explicit about which stage has whichever number of steps.

Also, since it's fairly easy to run any number of phases with arbitrary numbers of steps using `optimize`, this fits better.

I'd expect most people to use the default parameter values, which run t-SNE the same way as other implementations. If you go around tinkering with these parameters, you'd likely read the documentation, and you would likely understand what's what.

**Comment by dkobak** [comment]
I see. Don't think I agree :-) but it's your call. Feel free to close this
issue. What I would suggest though, is to write more explicitly in the
comments that this parameter is defined differently from other
implementations.

**Comment by pavlin-policar** [comment]
> What I would suggest though, is to write more explicitly in the
comments that this parameter is defined differently from other
implementations.

That's reasonable.
