### ISSUE TITLE
installing fftw3

### ISSUE THREAD

**Issue by bzip2** [pavlin-policar/openTSNE#73]
Hi. 

Could you provide a bit more detail about installing FFTW3, as you recommend [here](https://pypi.org/project/openTSNE/)? How does one verify that it's installed correctly and usable by openTSNE?  I followed the instructions for Ubuntu [here](http://micro.stanford.edu/wiki/Install_FFTW3),  namely `apt-get install libfftw3-dev libfftw3-doc`, and I see /usr/include/fftw3.h et al. Does this mean I have fftw3 installed correctly for openTSNE?

Thanks.

**Comment by pavlin-policar** [comment]
Hi, after installing fftw3, as you've done, you need to run the installation again, making sure that the cython files are recompiled. You can probably achieve this by reinstalling openTSNE using pip, or if you've cloned the repository, `python setup.py install`. The compilation will produce a lot of output, but you want to look for a line that says

> FFTW3 header files found. Using FFTW implementation of FFT.

This indicates that it's compiling against FFTW3 and not numpy. Also, if you're in this deep, you'll also want to verify that it's compiling with openmp flags - look for a similar message in the compilation output. This is much more important since, without openmp, opentsne will only be able to use one core. Almost all compilers support this, with the exception of some older mac versions of clang, and I guess the fix there is to just download a newer version of clang.

Let me know if you have any further questions.

**Comment by bzip2** [comment]
Perfect, thanks! That worked. I got the lines saying that the FFTW3 headers were found and that it compiled with openmp.

Just in case it's useful to others, apt was not a good way to install fftw3, at least with miniconda, which the apt command seems to have wrecked. I had been meaning to upgrade to anaconda anyway, used that to install [fftw3](https://anaconda.org/eumetsat/fftw3), then cloned and installed openTSNE as you suggested. Vroom vroom.

Thanks again, and also for adding to the tSNE universe the ability to reapply an embedding.
