### ISSUE TITLE
Don't see any effect of n_jobs

### ISSUE THREAD

**Issue by dkobak** [pavlin-policar/openTSNE#81]
Parameter `n_jobs` does not seem to influence the speed at all: I get exactly the same speed with `n_jobs=1` and `n_jobs=-1` (as well as other values) on my n=23k data set. It's weird -- what can I do to debug this?

**Comment by pavlin-policar** [comment]
Yes, there are ways this can happen. If you're installing openTSNE using conda, you're using prebuilt packages, which have been compiled ahead of time. Unfortunately, the conda servers use a clang compiler which doesn't support openMP, which is the library needed for multithreading in cython. Similarly, if you've installed openTSNE with pip and your clang compiler doesn't support openMP, there will have been a message during installation saying something along the lines of "openmp not found, things will run single core".

If you're using linux this shouldn't happen, and I'm unsure about windows, but I don't think this is a problem on windows either.

I know it's not ideal that this happens silently, but IMO it's better than not having packages at all.

**Comment by dkobak** [comment]
Hmm. I think I am confused. I am using Ubuntu and I think I used conda install. Your readme says

> In order for openTSNE to utilize multiple threads, the C/C++ compiler must also implement OpenMP. In practice, almost all compilers implement this with the exception of older version of clang on OSX systems.

so I thought that multithreading will work out of the box. But if I understood your comment correctly:

> If you're installing openTSNE using conda, you're using prebuilt packages, which have been compiled ahead of time. Unfortunately, the conda servers use a clang compiler which doesn't support openMP, which is the library needed for multithreading in cython.

it means that with multithreading will NOT work using conda install. Did I understand correctly? Should I re-install using pip?

**Comment by pavlin-policar** [comment]
> I am using Ubuntu and I think I used conda install.

The linux conda package should work properly out of the box. And since you're using a unix system you can easily check if all the right amount of cores is being used with `htop`.

As far as the conda packages and the entire build system, it's a bit messy and I haven't yet figured out how to get all the packages to compile with multithreading. But basically the issue is that the clang compiler, the C compiler used on macs, doesn't support openmp out of the box and some trickery is apparently required to make it work and it's a huge pain to get this working on conda and it's very tedious to debug. Apparently, newer versions of clang have openmp support, but the versions on the mac vms that conda uses have older versions. So openTSNE is compiled without multithreading support. So, when using a mac, it's better to install openTSNE from source 1) because people likely have newer versions of clang on their pcs and 2) because it's possible to debug things. Unfortunately, I don't have access to a mac so this is very difficult for me.

Linux uses gcc and windows uses the visual studio compiler, both of which support openmp out of the box, so multithreading should work straight away. When installing with `pip`, the install script will dynamically check for openmp and add the appropriate compiler flags as needed. And if openmp is not found, it prints out a message. Granted, you have to know to look for the message, but it's there.

I'd suggest you look at how many cores are being used using `htop` and if you find only a single core is being used, reinstall using pip and look for a line saying either

> Found openmp. Compiling with openmp flags...

or 

> You appear to be using a compiler which does not support openMP...

and if you see the latter message, check what the output of `cc -v` is to see which compiler is being used. On ubuntu, it should be gcc.

**Comment by dkobak** [comment]
Thanks. I won't be in the lab for the next two days, but will check afterwards and report back.

**Comment by dkobak** [comment]
So I wanted to investigate it and update my conda packages just in case, and now I am getting an error if I set `n_jobs` to any value apart from `n_jobs=1`. The error is in `nn_descent`:

```
~/anaconda3/lib/python3.6/site-packages/pynndescent/threaded.py in nn_descent(data, n_neighbors, rng_state, max_candidates, dist, dist_args, n_iters, delta, rho, rp_tree_init, leaf_array, verbose, n_jobs, seed_per_row)
    569         rng_state = new_rng_state()
    570 
--> 571     with joblib.Parallel(prefer="threads", n_jobs=n_jobs) as parallel:
    572 
    573         n_vertices = data.shape[0]

TypeError: __init__() got an unexpected keyword argument 'prefer'
```

Apologies if it's something on my side, because my conda now complains about some package inconsistencies and I didn't manage to solve it yet :-( I will try to fix it, but in the meanwhile am still reporting this just in case.

**Comment by pavlin-policar** [comment]
This is very strange indeed. My first thought was that the pynndescent API must have introduced a breaking change and no longer accepts a `n_jobs` parameter, but since they're still on v0.3.0, this can't be the case. It seems more likely that you're using an outdated version of `joblib` and that the `prefer` parameter was added in a later version. This would also indicate a versioning issue in `pynndescent`, where it doesn't rely on a late enough version of `joblib`. If this is indeed the case, you should report this to them.

**Comment by dkobak** [comment]
I will wait until today's 0.3.12 appears on conda, install the latest version on a new computer with fresh conda install and check if I still get this effect. Most likely it can be closed then.

**Comment by dkobak** [comment]
Hi Pavlin. So I installed 0.3.12 using conda on Linux with pynndescent 0.4, and tried it on full MNIST (70000x50 input data matrix after PCA). My laptop has 4 cores with 2 threads each, so 8 threads.

```
%time Z = TSNE(callbacks=ErrorLogger()).fit(X50)
```
runs around 3 min with every 50 iterations taking 7-8 seconds. In the system monitor I see 4 threads clocking at 100%.

```
%time Z = TSNE(callbacks=ErrorLogger(), n_jobs=1).fit(X50)
```
runs exactly the same time, again with 4 threads being active.

```
%time Z = TSNE(callbacks=ErrorLogger(), n_jobs=-1).fit(X50)
```
runs 1 min 45 sec with every 50 iterations taking 3-4 seconds, and all 8 threads running at 100%.

For comparison, FIt-SNE with default parameters took 1 min 2 sec, with every 50 iterations taking ~2 sec, and all 8 threads running at ~50%.

Q1) Are you sure that the default `n_jobs` value is -1? I get different results using -1 compared to the default.
Q2) Not sure why I have four threads at 100% with `n_jobs=1` (and not only one).
Q3) Not sure if the slowdown with `n_jobs=-1` compared to FIt-SNE is what should be expected due to the C++/Python difference (on the dataset of this size). Given that you have everything in numba, I expected the difference to be smaller...

**Comment by dkobak** [comment]
Oh I just realized that according to the docs the default value is `n_jobs=1`. This resolves my Q1, but why wouldn't you set `-1` as the default?

**Comment by pavlin-policar** [comment]
Hey Dmitry!

So the default number of threads is set to one to keep consistency with scikit-learn. I quite like that actually, so it doesn't automatically hogg all the threads unless I explicitly want it too. Since this is the default behavior in scikit-learn I think this is totally reasonable.

> In the system monitor I see 4 threads clocking at 100%.

So I suspect the reason for this is that you probably have a numpy binary that uses Intel MKL. I believe MKL will use multiple threads by default, and for if I run the following to just do a series of matrix multiplications, a very parallelizable operation,

```
CMD="import numpy as np
x = np.random.normal(0, 1, size=(5000, 5000))
print('Starting');
x @ x @ x @ x @ x @ x"
time python -c "$CMD"
```

I can see that 4 threads are at full utilization, but if I limit the number of threads MKL is allowed to use like this:

```
time MKL_NUM_THREADS=1 python -c "$CMD"
```

then it takes around 3x slower on my machine and only one thread is fully utilized.

This almost certainly comes into play in t-SNE. I also don't know how numba interacts with MKL, if at all, but it probably does make use of some of the MKL accelerations.

**Comment by dkobak** [comment]
Cool! Thanks a lot. I tried your code snippet and it does indeed utilize 4 threads by default.

So this answers my Q1 and Q2 and this issue can be closed which I am doing now. But I'm still curious what you think about Q3.

**Comment by pavlin-policar** [comment]
Yes, that big of a slowdown is a bit concerning and I'll have to look into it. The difference shouldn't be that large.

**Comment by dkobak** [comment]
Would definitely be good to look into what makes it slower. Is there any extra verbose ErrorLogger that can report how much time is spent on attactive/repulsive computations etc.?

**Comment by pavlin-policar** [comment]
No, unfortunately, the logging isn't the greatest. I had done the whole callback thing, which is useful in some contexts, but not the most appropriate for verbose messages. This is definitely I'd like to fix.
