### ISSUE TITLE
Is there any way to make 3D tSNEs with FIt-SNE/openTSNE?

### ISSUE THREAD

**Issue by davisidarta** [pavlin-policar/openTSNE#84]
##### Expected behaviour
I would expect the algorithm to be able to embed into 3 dimensions.

##### Actual behaviour
Documentation reports that only 2d embedding is available.

####What I want to do
Either:
-Embed 3 tSNE dimensions;
-To use the 2D tSNE coordinates outputted by FIt-SNE(openTSNE) with a third, Barnes-Hut calculated tSNE dimension.

I'm working with some highly diverse brain data from scRNAseq snapshots and a third dimension REALLY helps to visualize how the data is structured.

**Comment by dkobak** [comment]
FIt-SNE uses grid interpolation in the low-dimensional space, and its computational complexity would grow exponentially with the number of target dimensions. 3d embeddings are not supported because they would be too slow to compute. If you need to get a 3d embedding, the only available option is to use Barnes-Hut.

> I'm working with some highly diverse brain data from scRNAseq snapshots and a third dimension REALLY helps to visualize how the data is structured.

Do you have an example in mind? I worked with t-SNE a lot, but I've never seen an example where 3d visualisation would be more helpful than a 2d (apart from creating cool fly-through animations for public talks). Would be very curious to see one.

**Comment by davisidarta** [comment]
Hmmm, I see. I'll see if I can input a subsetted initialization first in order to alleviate Barnes-Hut computational expense. 

> Do you have an example in mind? I worked with t-SNE a lot, but I've never seen an example where 3d visualisation would be more helpful than a 2d (apart from creating cool fly-through animations for public talks). Would be very curious to see one.

I actually do. I'm studying the arcuate nucleus hypothalamic subpopulations for a while now, and there's a study in which they've made both 2d and 3d tSNE available. Several differentiation trajectories can only be visualized in the 3d plot (they look 'scrambled on the 2d plot'). You can check it [here](https://portals.broadinstitute.org/single_cell/study/SCP97/a-molecular-census-of-arcuate-hypothalamus-and-median-eminence-cell-types#study-visualize).

**Comment by dkobak** [comment]
> Several differentiation trajectories can only be visualized in the 3d plot (they look 'scrambled on the 2d plot'). You can check it here.

Thanks. I looked at both and I am willing to bet that it's because 2d visualization has not been done appropriately (e.g. they need to increase the learning rate). I did not work with 3d much myself, but my feeling is that in 3d there are fewer convergence problems: in 2d tSNE often gets stuck in a bad local minimum where similar clusters are separated in different parts of the visualization and cannot "get through" to each other. In 3d there is "more space" for them to navigate.

See here for how to mitigate this in 2d: https://www.biorxiv.org/content/10.1101/453449v2

**Comment by davisidarta** [comment]
I've already read that preprint from beginning to end \o/ ! It's been quite much my Bible during these last few days. 

> In 2d, tSNE with standard optimisation parameters often gets stuck in a bad local minimum where related clusters are separated in different parts of the visualization and cannot "get through" to each other.

Do you think this problem can be mitigated with the subsetted PCA-based initialization?

**Comment by dkobak** [comment]
Hahaha :)

Well, is it only n=20k as it says on the website? I don't think subsetting is needed for such a moderate sample size. I would use the same approach as we do with Tasic et al. data in the preprint: PCA init, learning rate n/12, look at perplexities 30 and n/100 and decide if you want to combine or choose one of them.

However, for the 3d vs. 2d issue, I am quite sure that they used the same initialisation (random) and the same perplexity. That's why I am thinking that maybe increasing the learning rate will be enough to make 2d not worse than 3d.

**Comment by davisidarta** [comment]
BTW: congratulations, that's going to be a great paper. I wish you good luck with the submitting process.

> Well, is it only n=20k as it says on the website?

(Un)fortunatelly no. I've integrated that dataset with several others that have been prepared for this same brain region. The full dataset is about 210k cells. I'll approach it as you suggested :)

> However, for the 3d vs. 2d issue, I am quite sure that they used the same initialisation (random) and the same perplexity. That's why I am thinking that maybe increasing the learning rate will be enough to make 2d not worse than 3d.

I see. Right now I'm trying to approach this with a huge mix of methods, including well-done tSNE. I hope its good enough!

Thanks for the suggestions

Cheers,
Davi

**Comment by pavlin-policar** [comment]
A little late to the party, but I'd agree with everything @dkobak has said. I would guess that the 2d-plot on the Broad website was obtained using the default parameters with random init, especially when comparing it to the 3d plot where there's some nice structure. Using Dmitry's tricks should get you a much better visualization.
